parameters: {}
environment:
  SPACES_ENDPOINT: "${SPACES_ENDPOINT}"
  SPACES_NAME: "${SPACES_NAME}"
  SPACES_KEY: "${SPACES_KEY}"
  SPACES_SECRET: "${SPACES_SECRET}"
packages:
    - name: images
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: save
          binary: false
          main: ""
          runtime: nodejs:14
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
